# Base configs
baseurl: "https://bartoszstawski.github.io/portfolio/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Bartosz Stawski Fotografia"
subtitle: "Portfolio"
author: "Bartosz Stawski"
header:
 title: "Bartosz Stawski"
 subtitle: "Fotografia"
footer:
 name: ""
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/bartek.stawski.5"
  instagram: "https://www.instagram.com/bart_s_photo"
